[package]
name = "nativelink-error"
version = "0.4.0"
edition = "2021"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[dependencies]
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }
hex = { version = "0.4.3", default-features = false }
prost = { version = "0.13.1", default-features = false }
prost-types = { version = "0.13.1", default-features = false }
redis = { version = "0.25.4", default-features = false }
serde = { version = "1.0.204", default-features = false }
tokio = { version = "1.38.0" }
tonic = { version = "0.12.0", default-features = false }
