[package]
name = "nativelink-worker"
version = "0.5.1"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-store = { path = "../nativelink-store" }
nativelink-metric = { path = "../nativelink-metric" }
async-lock = { version = "3.4.0", features = ["std"], default-features = false }
bytes = { version = "1.6.1", default-features = false }
filetime = "0.2.23"
formatx = "0.2.2"
futures = { version = "0.3.30", default-features = false }
parking_lot = "0.12.3"
prost = { version = "0.13.1", default-features = false }
relative-path = "1.9.3"
scopeguard = { version = "1.2.0", default-features = false }
serde = { version = "1.0.204", default-features = false }
serde_json5 = "0.1.0"
shlex = { version = "1.3.0", default-features = false }
tokio = { version = "1.38.0", features = ["process", "fs", "rt-multi-thread", "signal", "io-util"], default-features = false }
tokio-stream = { version = "0.1.15", default-features = false, features = ["fs"] }
tonic = { version = "0.12.0", features = ["gzip", "tls", "transport"], default-features = false }
tracing = { version = "0.1.40", default-features = false }
uuid = { version = "1.10.0", default-features = false, features = ["v4", "serde"] }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

hyper = "1.4.1"
hyper-util = "0.1.6"
once_cell = { version = "1.19.0", default-features = false }
pretty_assertions = { version = "1.4.0", features = ["std"] }
prost-types = { version = "0.13.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
