[package]
name = "nativelink-service"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-proto = { path = "../nativelink-proto" }
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-store = { path = "../nativelink-store" }
nativelink-scheduler = { path = "../nativelink-scheduler" }
axum = { version = "0.7.5", default-features = false }
bytes = { version = "1.6.1", default-features = false }
futures = { version = "0.3.30", default-features = false }
http-body = "1.0.1"
http-body-util = "0.1.2"
hyper = { version = "1.4.1" }
serde_json5 = "0.1.0"
parking_lot = "0.12.3"
prost = { version = "0.13.1", default-features = false }
tokio = "1.38.0"
tokio-stream = { version = "0.1.15", default-features = false }
tonic = { version = "0.12.0", default-features = false }
tower = { version = "0.4.13", default-features = false }
tracing = { version = "0.1.40", default-features = false }
uuid = { version = "1.10.0", default-features = false }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }
nativelink-metric = { path = "../nativelink-metric" }

async-trait = "0.1.80"
async-lock = { version = "3.3.0", default-features = false }
hyper = "1.4.1"
hyper-util = "0.1.6"
maplit = "1.0.2"
pretty_assertions = { version = "1.4.0", features = ["std"] }
prost-types = { version = "0.13.1", default-features = false }
