[package]
name = "nativelink-config"
version = "0.4.0"
edition = "2021"

[dependencies]
byte-unit = { version = "5.1.4", default-features = false, features = ["byte"] }
humantime = "2.1.0"
serde = { version = "1.0.204", default-features = false }
serde_json5 = "0.1.0"
shellexpand = { version = "3.1.0", default-features = false, features = ["base-0"] }

[dev-dependencies]
pretty_assertions = { version = "1.4.0", features = ["std"] }
