---
name: Sanitizers

on:
  push:
    branches: [ "fake" ]
  pull_request:
    branches: [ "fake" ]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  sanitized-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        sanitizer: [asan]
    name: ${{ matrix.sanitizer }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Bazelisk
        uses: >- # v0.8.1
          bazel-contrib/setup-bazel@b388b84bb637e50cdae241d0f255670d4bd79f29
        with:
          bazelisk-cache: true
          repository-cache: true

      - name: Run Bazel tests
        run: bazel test --config=${{ matrix.sanitizer }} --verbose_failures //...
        shell: bash
